// 389. Find the Difference  QuestionEditorial Solution  My Submissions
// Total Accepted: 8067
// Total Submissions: 15863
// Difficulty: Easy
// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
	for (var i = 1; i < s.length; i++) {
		s[i] = s[i] ^ (s[i-1] ^ t[i-1])
	}
	return s[i-1]^t[i-1]^t[i]
    
};

// 这题给两个string但是其实跟single number那题是一样的啊，只有一个是不同的，用位操作！
// 基本思想是这样，但是语法有问题